### ISSUE TITLE
[BUG] Cannot set more than 2 homes in config file

### ISSUE THREAD

**Issue by blacktoz** [devblook/shrimp#2]
When setting up more than 2 homes, it shows this, which is normal, since the config file is set at 2 homes :
![image](https://user-images.githubusercontent.com/34444000/232788154-6090ae25-d3d7-4b7f-890f-2e7405e7eea8.png)
Now, when you change the value to any number, like 10 as I did, when I reboot the server, it completely ignores it and modifies my value by "2"
![image](https://user-images.githubusercontent.com/34444000/232788666-626ce964-251b-43d8-83ed-ac4dbb024e6b.png)

**Comment by Call4han** [comment]
hello sir use command /shrimp reload
to reload the configuration.

**Comment by Call4han** [comment]
![imagen](https://user-images.githubusercontent.com/95487773/232802584-bb5a485c-b34b-4a3c-8c7a-915611ec8925.png)

**Comment by blacktoz** [comment]
yep, that worked great, thanks!
